export const DEFAULT_TIMEOUT = 10000; // 10 seconds
export const MAX_CONCURRENT_REQUESTS = 3;
export const MAX_DEPTH = 2;

export const USER_AGENT = 'Mozilla/5.0 (compatible; JobScraperBot/1.0; +http://example.com/bot)';

export const COMMON_EXECUTIVE_KEYWORDS = [
  'CEO', 'Founder', 'Vice President', 'Chief Executive Officer', 'Chief Operating Officer', 'Manager', 'Director', 'CTO', 'Chief Technical Officer',
  'Lead', 'CFO', 'Chief Financial Officer', 'COO', 'Chief People Officer', 'VP of Talent Acquisition',
  'VP of People', 'Chief of Staff', 'Head of Talent Acquisition,', 'Head of People', 'VP of Engineering', 'VP of Operations', 'Director of Engineering',
  'Recruiter', 'associate', 'assistant', 'intern'
];

export const serp_query_one = 'leadership team OR board of directors OR executive profiles'
export const serp_query_two = 'CEO OR Chief Executive Officer OR Chief Operating Officer OR executive team OR management team OR board members OR company executives'
export const serp_query_three = 'talent partner OR hiring manager OR head of people OR head of talent OR talent acquisition'

export const TESTING_DOMAINS = [ 
'https://www.arobiotx.com', 
'https://arqu.co', 
'https://thearriveplatform.com/', 
'https://artbio.com', 
'https://www.artisight.com', 
'http://www.shipartyc.com/', 
'https://www.ascidian-tx.com/', 
'https://www.assetwatch.com/', 
'https://www.astroforge.io', 
'https://www.atlys.com', 
'https://atomic.ai/', 
'http://www.atroposhealth.com', 
'https://attentive.ai', 
'https://www.attochron.com', 
'https://www.attotude.com', 
'https://www.attovia.com', 
'https://www.augmentcode.com', 
'https://auradine.com', 
'https://authenticinsurance.com/', 
'http://authorhealth.com', 
'https://authzed.com', 
'https://autify.com', 
'https://www.auxili.us/', 
'https://www.avive.life', 
'https://www.axiom.xyz/', 
'https://www.axionray.com', 
'https://www.axuall.com', 
'https://axur.com', 
'https://azragames.com', 
'https://www.bgarage.ai', 
'https://balto.ai', 
'https://bandana.com/', 
'https://baseoperations.com', 
'https://www.baseten.co', 
'https://www.bazookatango.com/', 
'https://beaconai.co', 
'https://beacons.ai', 
'http://beatthebomb.com', 
'https://bedrockocean.com', 
'http://www.getbenepass.com', 
'https://joinbetter.com/', 
'https://www.betteromics.com', 
'https://www.betteryou.ai', 
'https://bighappy.co/', 
'https://bikky.com', 
'https://www.billgo.com', 
'https://biocentriq.com', 
'https://smartgun.com', 
'http://www.bionautlabs.com', 
'https://getbite.com', 
'https://www.blackbird.xyz', 
'https://www.blackcloak.io', 
'https://www.bland.ai', 
'https://www.blerp.com', 
'http://www.bloomlife.com', 
'http://bhtherapeutics.com', 
'https://bluefrontierac.com', 
'https://blueprint.ai', 
'https://www.blumira.com', 
'https://www.agebold.com/', 
'https://bolster.ai', 
'https://www.boweryvaluation.com', 
'https://www.boxbot.io/', 
'https://www.braintrustdata.com', 
'http://www.branch.technology/', 
'https://www.bridge.xyz', 
'https://www.brightband.com/', 
'https://burnbot.com', 
'https://burro.ai', 
'https://busright.com', 
'https://www.butlr.com', 
'http://www.caelux.com', 
'https://caldera.xyz', 
'https://cacultured.com/', 
'https://calyxtechs.com/', 
'https://cambium-usa.com', 
'http://campus.edu', 
'https://www.candex.com', 
'https://www.joincandidhealth.com', 
'https://canopyservicing.com/', 
'https://usecanopy.com', 
'https://www.cape.co/', 
'https://www.hicapitalize.com', 
'https://capstanmedical.com/', 
'https://www.caraway.health', 
'https://www.carbonated.com/', 
'https://carboncapture.com/', 
'http://www.carbonquest.com', 
'https://www.carewell.com', 
'https://www.cargobot.io/', 
'https://carrymoney.com/', 
'https://www.cartwheelcare.org', 
'https://www.cast.ai/'
];