export const DEFAULT_TIMEOUT = 10000; // 10 seconds
export const MAX_CONCURRENT_REQUESTS = 3;
export const MAX_DEPTH = 2;

export const USER_AGENT =
  "Mozilla/5.0 (compatible; JobScraperBot/1.0; +http://example.com/bot)";

export const KEYWORDS = [
  "leadership",
  "co-founder",
  "team",
  "executive",
  "board",
  "leaders",
  "directors",
  "position",
  "role",
  "ceo",
  "president",
  "cfo",
  "coo",
  "chief",
  "vp",
  "vice president",
  "management",
  "founder",
  "partner",
  "owner",
  "officer",
  "chair",
  "principal",
  "advisor",
  "head",
  "executive team",
  "leadership team",
  "senior management",
  "company officers",
  "key personnel",
  "corporate officers",
  "governance",
  "administration",
  "executive committee",
  "managing director",
];

export const CRUST_POSITIONS = [
  "Founder",
  "Co-Founder",
  "CEO",
  "CTO",
  "COO",
  "Chief People Officer",
  "VP of Talent",
  "VP of People",
  "Chief of staff",
  "Head of Talent",
  "Vice President of Talent",
  "Head of People",
  "VP of Engineering",
  "VP of Operations",
  "Director of Engineering",
  "CFO",
  "VP of Sales",
  "CMO",
];

export const COMMON_EXECUTIVE_KEYWORDS = [
  "CEO",
  "Founder",
  "Vice President",
  "Chief Executive Officer",
  "Chief Operating Officer",
  "Manager",
  "Director",
  "CTO",
  "Chief Technical Officer",
  "Lead",
  "CFO",
  "Chief Financial Officer",
  "COO",
  "Chief People Officer",
  "VP of Talent Acquisition",
  "VP of People",
  "Chief of Staff",
  "Head of Talent Acquisition,",
  "Head of People",
  "VP of Engineering",
  "VP of Operations",
  "Director of Engineering",
  "Recruiter",
  "associate",
  "assistant",
  "intern",
];

export const serp_query_one =
  "leadership team OR board of directors OR executive profiles";
export const serp_query_two = "talent acquisition manager OR head of talent";
export const serp_query_three = "head of people OR chief people officer";
export const serp_query_four = "CTO OR CEO OR Head of Engineering";

export const testing_domains = [
  "https://x.ai",
  "https://helloalice.com",
  "https://www.together.ai",
  "https://legion.co",
  "https://www.ioncleanenergy.com/",
  "http://www.nironmagnetics.com",
  "https://auradine.com",
  "https://dapps-eigenlayer.xyz",
  "https://www.databento.com/",
  "https://www.apptega.com",
  "https://sigmasense.com",
  "https://bolster.ai",
  "http://www.cleargov.com",
  "http://www.atroposhealth.com",
  "http://www.xonaspace.com",
  "https://www.cayosoft.com",
  "https://www.novata.com/",
  "https://www.cruxdata.com/",
  "https://sayari.com",
  "https://certifid.com",
  "https://www.espressosys.com/",
  "https://loft.sh/",
  "https://www.elisity.com/",
  "https://co.bot",
  "https://www.todyl.com/",
  "https://www.doola.com/",
  "https://arc.net",
  "https://weavix.com/",
  "http://brain.ai",
  "https://www.pdw.ai/",
  "https://amdilabs.com",
  "https://askchapter.org/",
  "https://nacelle.com",
  "https://www.capstack.ai",
  "http://moderawealth.com/",
  "https://www.fieldguide.io",
  "https://www.lumos.com/",
  "https://www.worldview.space",
  "https://www.plumenetwork.xyz/",
  "http://cariloop.com",
  "https://www.prefect.io",
  "https://truflation.com/",
  "https://oden.io",
  "http://www.tinkermode.com/mode",
  "https://peregrine.io",
  "https://www.arbol.io/",
  "https://www.Blockitnow.com",
  "https://safebase.io",
  "http://www.champtitles.com",
  "https://www.sifthealthcare.com",
  "https://www.empathy.com/",
  "https://nlx.ai",
  "http://www.ecotrak.com/",
  "https://www.guardian.ag",
  "https://www.synadia.com/",
  "https://hume.ai",
  "http://www.grammatech.com",
  "http://validmind.com",
  "https://www.quilt.com/",
  "https://anvilogic.com",
  "https://exploreomni.com",
  "https://www.highbyte.com",
  "https://www.abett.com/",
  "https://rivet.work",
  "https://www.cape.co/",
  "https://coactive.ai",
  "http://colovore.com",
  "https://www.dripos.com",
  "https://www.bcore.com",
  "https://www.tarsal.co",
  "https://ursaspace.com",
  "https://upflow.io",
  "https://getbite.com",
  "https://www.shelterzoom.com/",
  "https://simbian.ai",
  "https://www.clinicalresearch.io/",
  "https://zanskar.us",
  "https://bedrock.security",
  "https://www.pipedreams.com",
  "https://efficient.computer/",
  "https://www.evosecurity.com",
  "https://www.expanso.io",
  "https://neubird.ai/",
  "https://www.draftwise.com/",
  "https://www.finaloffer.com/",
  "https://www.auxili.us/",
  "https://passes.com",
  "https://www.alethea.com/",
  "https://www.privateer.com",
  "https://www.muralhealth.com",
  "https://www.withluminary.com/",
  "https://www.hdata.us",
  "http://www.theradaptive.com",
  "https://www.vorlonsecurity.com",
  "https://www.ohanafy.com",
  "https://www.zafran.io",
  "http://www.stratyfy.com",
  "https://www.opmed.ai/",
  "https://retextion.com/",
  "http://www.nmsdc.org/",
  "https://baselayerhq.com/",
  "https://www.lokker.com/",
  "http://buzzsolutions.co/",
  "http://www.simulations-plus.com",
  "https://www.pump.co",
  "https://blackwellsecurity.com",
  "https://www.sprocketsecurity.com/",
  "https://reach.security/",
  "https://www.toku.com",
  "https://www.vizcom.ai",
  "https://www.sagetap.io",
  "https://www.quintessent.com/",
  "https://niobiummicrosystems.com/",
  "https://buildforce.com/",
  "https://onenotary.us",
  "https://www.withdaydream.com/",
  "https://www.thefolklore.com",
  "https://prompt.io",
  "https://dosu.dev/",
  "https://www.peoplereign.io/",
  "https://www.zulupods.com",
  "https://www.openpipe.ai/",
  "http://www.accelo.com",
  "https://tryloop.ai/",
  "https://newhomesmate.com/",
  "https://abstract.us",
  "https://cyvl.ai/",
  "https://insanecyber.com",
  "https://anthropos.work",
  "http://www.rallyuxr.com",
  "https://bettercomp.com",
  "https://www.activatework.org/",
  "https://indicio.tech",
  "https://www.byrevive.com/",
  "https://www.instantconnectnow.com",
  "https://www.kefrobotics.com/",
  "https://www.withremark.com",
  "https://codified.io",
  "https://www.getzep.com/",
  "https://moonware.com",
  "https://www.stxn.io",
  "https://www.solstarspace.com/",
  "https://sobet.io",
  "http://www.zoomph.com",
  "https://resonance.security",
  "http://www.optiyol.com",
  "https://wisprsystems.com/",
  "https://churnkey.co/",
  "https://muuktest.com/",
  "https://paladincloud.io",
  "http://www.inspace.app",
  "https://travelsist.com",
  "https://www.gesund.ai",
  "https://www.luminolabs.ai",
];
